
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeleteBookingService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost:8080/wsdl/timewriterapi.wsdl")
public class DeleteBookingService
    extends Service
{

    private final static URL DELETEBOOKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELETEBOOKINGSERVICE_EXCEPTION;
    private final static QName DELETEBOOKINGSERVICE_QNAME = new QName("api.timewriter.soap.nl", "DeleteBookingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELETEBOOKINGSERVICE_WSDL_LOCATION = url;
        DELETEBOOKINGSERVICE_EXCEPTION = e;
    }

    public DeleteBookingService() {
        super(__getWsdlLocation(), DELETEBOOKINGSERVICE_QNAME);
    }

    public DeleteBookingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELETEBOOKINGSERVICE_QNAME, features);
    }

    public DeleteBookingService(URL wsdlLocation) {
        super(wsdlLocation, DELETEBOOKINGSERVICE_QNAME);
    }

    public DeleteBookingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELETEBOOKINGSERVICE_QNAME, features);
    }

    public DeleteBookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteBookingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeleteBookingServicePort
     */
    @WebEndpoint(name = "DeleteBookingServicePort")
    public DeleteBookingServicePort getDeleteBookingServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteBookingServicePort"), DeleteBookingServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteBookingServicePort
     */
    @WebEndpoint(name = "DeleteBookingServicePort")
    public DeleteBookingServicePort getDeleteBookingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteBookingServicePort"), DeleteBookingServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELETEBOOKINGSERVICE_EXCEPTION!= null) {
            throw DELETEBOOKINGSERVICE_EXCEPTION;
        }
        return DELETEBOOKINGSERVICE_WSDL_LOCATION;
    }

}
