
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeleteAspectService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost:8080/wsdl/timewriterapi.wsdl")
public class DeleteAspectService
    extends Service
{

    private final static URL DELETEASPECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELETEASPECTSERVICE_EXCEPTION;
    private final static QName DELETEASPECTSERVICE_QNAME = new QName("api.timewriter.soap.nl", "DeleteAspectService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELETEASPECTSERVICE_WSDL_LOCATION = url;
        DELETEASPECTSERVICE_EXCEPTION = e;
    }

    public DeleteAspectService() {
        super(__getWsdlLocation(), DELETEASPECTSERVICE_QNAME);
    }

    public DeleteAspectService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELETEASPECTSERVICE_QNAME, features);
    }

    public DeleteAspectService(URL wsdlLocation) {
        super(wsdlLocation, DELETEASPECTSERVICE_QNAME);
    }

    public DeleteAspectService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELETEASPECTSERVICE_QNAME, features);
    }

    public DeleteAspectService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteAspectService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeleteAspectServicePort
     */
    @WebEndpoint(name = "DeleteAspectServicePort")
    public DeleteAspectServicePort getDeleteAspectServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteAspectServicePort"), DeleteAspectServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteAspectServicePort
     */
    @WebEndpoint(name = "DeleteAspectServicePort")
    public DeleteAspectServicePort getDeleteAspectServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteAspectServicePort"), DeleteAspectServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELETEASPECTSERVICE_EXCEPTION!= null) {
            throw DELETEASPECTSERVICE_EXCEPTION;
        }
        return DELETEASPECTSERVICE_WSDL_LOCATION;
    }

}
