
package timewriter.soap.api;

import timewriter.object.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeleteAspectServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeleteAspectServicePort {


    /**
     * 
     * @param securityToken
     * @param id
     * @return
     *     returns timewriter.object.DeleteAspectResult
     */
    @WebMethod(operationName = "DeleteAspect", action = "DeleteAspect")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "DeleteAspect", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.DeleteAspect")
    @ResponseWrapper(localName = "DeleteAspectResponse", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.DeleteAspectResponse")
    public DeleteAspectResult deleteAspect(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "id", targetNamespace = "")
        long id);

}
