
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeleteRelationService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost/wsdl/timewriterapi.wsdl")
public class DeleteRelationService
    extends Service
{

    private final static URL DELETERELATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELETERELATIONSERVICE_EXCEPTION;
    private final static QName DELETERELATIONSERVICE_QNAME = new QName("api.timewriter.soap.nl", "DeleteRelationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELETERELATIONSERVICE_WSDL_LOCATION = url;
        DELETERELATIONSERVICE_EXCEPTION = e;
    }

    public DeleteRelationService() {
        super(__getWsdlLocation(), DELETERELATIONSERVICE_QNAME);
    }

    public DeleteRelationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELETERELATIONSERVICE_QNAME, features);
    }

    public DeleteRelationService(URL wsdlLocation) {
        super(wsdlLocation, DELETERELATIONSERVICE_QNAME);
    }

    public DeleteRelationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELETERELATIONSERVICE_QNAME, features);
    }

    public DeleteRelationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteRelationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeleteRelationServicePort
     */
    @WebEndpoint(name = "DeleteRelationServicePort")
    public DeleteRelationServicePort getDeleteRelationServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteRelationServicePort"), DeleteRelationServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteRelationServicePort
     */
    @WebEndpoint(name = "DeleteRelationServicePort")
    public DeleteRelationServicePort getDeleteRelationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "DeleteRelationServicePort"), DeleteRelationServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELETERELATIONSERVICE_EXCEPTION!= null) {
            throw DELETERELATIONSERVICE_EXCEPTION;
        }
        return DELETERELATIONSERVICE_WSDL_LOCATION;
    }

}
