
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetAspectsServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetAspectsServicePort {


    /**
     * 
     * @param securityToken
     * @param aspectType
     * @param filters
     * @return
     *     returns timewriter.object.GetAspectsResult
     */
    @WebMethod(operationName = "GetAspects", action = "GetAspects")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetAspects", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.GetAspects")
    @ResponseWrapper(localName = "GetAspectsResponse", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.GetAspectsResponse")
    public GetAspectsResult getAspects(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "aspectType", targetNamespace = "")
        String aspectType,
        @WebParam(name = "filters", targetNamespace = "")
        Filters filters);

}
