
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAspectsService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost:8080/wsdl/timewriterapi.wsdl")
public class GetAspectsService
    extends Service
{

    private final static URL GETASPECTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETASPECTSSERVICE_EXCEPTION;
    private final static QName GETASPECTSSERVICE_QNAME = new QName("api.timewriter.soap.nl", "GetAspectsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETASPECTSSERVICE_WSDL_LOCATION = url;
        GETASPECTSSERVICE_EXCEPTION = e;
    }

    public GetAspectsService() {
        super(__getWsdlLocation(), GETASPECTSSERVICE_QNAME);
    }

    public GetAspectsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETASPECTSSERVICE_QNAME, features);
    }

    public GetAspectsService(URL wsdlLocation) {
        super(wsdlLocation, GETASPECTSSERVICE_QNAME);
    }

    public GetAspectsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETASPECTSSERVICE_QNAME, features);
    }

    public GetAspectsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAspectsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAspectsServicePort
     */
    @WebEndpoint(name = "GetAspectsServicePort")
    public GetAspectsServicePort getGetAspectsServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "GetAspectsServicePort"), GetAspectsServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAspectsServicePort
     */
    @WebEndpoint(name = "GetAspectsServicePort")
    public GetAspectsServicePort getGetAspectsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "GetAspectsServicePort"), GetAspectsServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETASPECTSSERVICE_EXCEPTION!= null) {
            throw GETASPECTSSERVICE_EXCEPTION;
        }
        return GETASPECTSSERVICE_WSDL_LOCATION;
    }

}
