
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetRelationsServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetRelationsServicePort {


    /**
     * 
     * @param securityToken
     * @param relationType
     * @param id2
     * @param id1
     * @param filters
     * @return
     *     returns nl.soap.timewriter.api.GetRelationsResult
     */
    @WebMethod(operationName = "GetRelations", action = "GetRelations")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetRelations", targetNamespace = "api.timewriter.soap.nl", className = "nl.soap.timewriter.api.GetRelations")
    @ResponseWrapper(localName = "GetRelationsResponse", targetNamespace = "api.timewriter.soap.nl", className = "nl.soap.timewriter.api.GetRelationsResponse")
    public GetRelationsResult getRelations(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "id1", targetNamespace = "")
        long id1,
        @WebParam(name = "id2", targetNamespace = "")
        long id2,
        @WebParam(name = "relationType", targetNamespace = "")
        String relationType,
        @WebParam(name = "filters", targetNamespace = "")
        Filters filters);

}
