
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldServicePort", targetNamespace = "api.timewriter.soap.nl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldServicePort {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "HelloWorld")
    @WebResult(name = "HelloWorldResponse", targetNamespace = "api.timewriter.soap.nl", partName = "response")
    public String helloWorld(
        @WebParam(name = "HelloWorldRequest", targetNamespace = "api.timewriter.soap.nl", partName = "request")
        String request);

}
