
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginServicePort {


    /**
     * 
     * @param apiKey
     * @param softwareDesc
     * @param userKey
     * @return
     *     returns nl.soap.timewriter.api.LoginResult
     */
    @WebMethod(operationName = "Login", action = "Login")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "Login", targetNamespace = "api.timewriter.soap.nl", className = "nl.soap.timewriter.api.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "api.timewriter.soap.nl", className = "nl.soap.timewriter.api.LoginResponse")
    public LoginResult login(
        @WebParam(name = "api_key", targetNamespace = "")
        String apiKey,
        @WebParam(name = "user_key", targetNamespace = "")
        String userKey,
        @WebParam(name = "softwareDesc", targetNamespace = "")
        String softwareDesc);

}
