
package timewriter.soap.api;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogoutServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogoutServicePort {


    /**
     * 
     * @param securityToken
     */
    @WebMethod(operationName = "Logout", action = "Logout")
    @Oneway
    @RequestWrapper(localName = "Logout", targetNamespace = "api.timewriter.soap.nl", className = "nl.soap.timewriter.api.Logout")
    public void logout(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken);

}
