
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateBookingServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateBookingServicePort {


    /**
     * 
     * @param securityToken
     * @param booking
     * @param roundTimes
     * @return
     *     returns timewriter.object.UpdateBookingResult
     */
    @WebMethod(operationName = "UpdateBooking", action = "UpdateBooking")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "UpdateBooking", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateBooking")
    @ResponseWrapper(localName = "UpdateBookingResponse", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateBookingResponse")
    public UpdateBookingResult updateBooking(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "booking", targetNamespace = "")
        Booking booking,
        @WebParam(name = "roundTimes", targetNamespace = "")
        boolean roundTimes);

}
