
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateRelationService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost:8080/wsdl/timewriterapi.wsdl")
public class UpdateRelationService
    extends Service
{

    private final static URL UPDATERELATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATERELATIONSERVICE_EXCEPTION;
    private final static QName UPDATERELATIONSERVICE_QNAME = new QName("api.timewriter.soap.nl", "UpdateRelationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATERELATIONSERVICE_WSDL_LOCATION = url;
        UPDATERELATIONSERVICE_EXCEPTION = e;
    }

    public UpdateRelationService() {
        super(__getWsdlLocation(), UPDATERELATIONSERVICE_QNAME);
    }

    public UpdateRelationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATERELATIONSERVICE_QNAME, features);
    }

    public UpdateRelationService(URL wsdlLocation) {
        super(wsdlLocation, UPDATERELATIONSERVICE_QNAME);
    }

    public UpdateRelationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATERELATIONSERVICE_QNAME, features);
    }

    public UpdateRelationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateRelationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateRelationServicePort
     */
    @WebEndpoint(name = "UpdateRelationServicePort")
    public UpdateRelationServicePort getUpdateRelationServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "UpdateRelationServicePort"), UpdateRelationServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateRelationServicePort
     */
    @WebEndpoint(name = "UpdateRelationServicePort")
    public UpdateRelationServicePort getUpdateRelationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "UpdateRelationServicePort"), UpdateRelationServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATERELATIONSERVICE_EXCEPTION!= null) {
            throw UPDATERELATIONSERVICE_EXCEPTION;
        }
        return UPDATERELATIONSERVICE_WSDL_LOCATION;
    }

}
