
package timewriter.soap.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateRelationServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateRelationServicePort {


    /**
     * 
     * @param securityToken
     * @param relation
     * @return
     *     returns timewriter.object.UpdateRelationResult
     */
    @WebMethod(operationName = "UpdateRelation", action = "UpdateRelation")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "UpdateRelation", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateRelation")
    @ResponseWrapper(localName = "UpdateRelationResponse", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateRelationResponse")
    public UpdateRelationResult updateRelation(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "relation", targetNamespace = "")
        Relation relation);

}
