
package timewriter.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateBookingService", targetNamespace = "api.timewriter.soap.nl", wsdlLocation = "http://localhost/wsdl/timewriterapi.wsdl")
public class UpdateBookingService
    extends Service
{

    private final static URL UPDATEBOOKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATEBOOKINGSERVICE_EXCEPTION;
    private final static QName UPDATEBOOKINGSERVICE_QNAME = new QName("api.timewriter.soap.nl", "UpdateBookingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/timewriterapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATEBOOKINGSERVICE_WSDL_LOCATION = url;
        UPDATEBOOKINGSERVICE_EXCEPTION = e;
    }

    public UpdateBookingService() {
        super(__getWsdlLocation(), UPDATEBOOKINGSERVICE_QNAME);
    }

    public UpdateBookingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEBOOKINGSERVICE_QNAME, features);
    }

    public UpdateBookingService(URL wsdlLocation) {
        super(wsdlLocation, UPDATEBOOKINGSERVICE_QNAME);
    }

    public UpdateBookingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEBOOKINGSERVICE_QNAME, features);
    }

    public UpdateBookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateBookingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateBookingServicePort
     */
    @WebEndpoint(name = "UpdateBookingServicePort")
    public UpdateBookingServicePort getUpdateBookingServicePort() {
        return super.getPort(new QName("api.timewriter.soap.nl", "UpdateBookingServicePort"), UpdateBookingServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateBookingServicePort
     */
    @WebEndpoint(name = "UpdateBookingServicePort")
    public UpdateBookingServicePort getUpdateBookingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("api.timewriter.soap.nl", "UpdateBookingServicePort"), UpdateBookingServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEBOOKINGSERVICE_EXCEPTION!= null) {
            throw UPDATEBOOKINGSERVICE_EXCEPTION;
        }
        return UPDATEBOOKINGSERVICE_WSDL_LOCATION;
    }

}
