
package timewriter.soap.api;

import timewriter.object.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import timewriter.object.*;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateAspectServicePort", targetNamespace = "api.timewriter.soap.nl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateAspectServicePort {


    /**
     * 
     * @param securityToken
     * @param aspect
     * @return
     *     returns timewriter.object.UpdateAspectResult
     */
    @WebMethod(operationName = "UpdateAspect", action = "UpdateAspect")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "UpdateAspect", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateAspect")
    @ResponseWrapper(localName = "UpdateAspectResponse", targetNamespace = "api.timewriter.soap.nl", className = "timewriter.object.UpdateAspectResponse")
    public UpdateAspectResult updateAspect(
        @WebParam(name = "securityToken", targetNamespace = "")
        String securityToken,
        @WebParam(name = "aspect", targetNamespace = "")
        Aspect aspect);

}
